Task/62
habralab/sapphire-team-back pull request #32
Opened 2023-10-02 12:49 UTC by brulitsan

2023-10-02 14:31 UTC, OlegYurchik commented on sapphire/projects/database/cli.py
> +    app(db_dsn="sqlite+aiosqlite:///projects.sqlite3")
На самом верхнем уровне (sapphire/cli.py) у нас есть метод `get_cli`, который подключает cli, которые на уровень ниже (их мы получаем через `get_cli`) и так далее. Делая запуска cli здесь - ты ломаешь всю цепочку.
[Пример](https://github.com/OlegYurchik/dresscode_bot/blob/main/dresscode_bot/cli.py)
+
Непонятно, почему используем захардкоженный db_dsn. А если хотим использовать другой?

2023-10-02 14:31 UTC, OlegYurchik commented on sapphire/projects/database/cli.py
> +    service = BaseDatabaseService(db_dsn)
[Вот класс базы данных](https://github.com/habralab/sapphire-team-back/blob/main/sapphire/users/database/service.py)
И тут есть метод `get_service`
db_dsn можно взять из настроек, которые находятся в контексте
[Пример](https://github.com/habralab/sapphire-team-back/blob/main/sapphire/users/api/cli.py#L13)

2023-10-02 15:57 UTC, brulitsan commented on sapphire/projects/database/cli.py
> +    service = BaseDatabaseService(db_dsn)
так, вижу, что часть исправил, но не все

2023-10-03 03:58 UTC, OlegYurchik commented on sapphire/projects/database/cli.py
> +    migration = BaseDatabaseService(dsn=settings)
Мы не используем базовый класс здесь, так как он в принципе не может работать (попробуй запустить его просто из тестового файла и он выдаст ошибку NotImplementedError). Базовые классы существуют для того, чтобы хранить общую структуру и логику, от них мы наследуемся и создаём новые классы [Пример](https://github.com/habralab/sapphire-team-back/blob/main/sapphire/users/database/service.py) и уже с ними работаем

2023-10-03 03:58 UTC, OlegYurchik commented on sapphire/projects/database/cli.py
> +def create_migration(ctx: typer.Context):
Просто `create`

2023-10-03 03:58 UTC, OlegYurchik commented on sapphire/projects/database/cli.py
> +    cli.command(name="create_migration")(create_migration)
Просто `create`

2023-10-03 04:11 UTC, OlegYurchik commented
https://github.com/habralab/sapphire-team-back/blob/main/sapphire/users/api/cli.py#L15

Вот так сервис базы данных берётся в сервисе users. Нам в projects нужен свой сервис базы данных (его нужно создать) и сделать две cli команды - `migrate` и `create`

2023-10-03 09:32 UTC, vanvanich9 commented on sapphire/projects/database/cli.py
> +# pylint: disable=duplicate-code
в новом .pylintrc уже есть `disable=duplicate-code`
писать этот комментарий больше не нужно

если у тебя нет, сделай rebase от главной ветки

2023-10-04 11:09 UTC, OlegYurchik commented on tests/common/test_package.py
> +import pytest
Зачем два раза pytest импортировать?

2023-10-04 12:52 UTC, OlegYurchik requested changes

2023-10-04 12:52 UTC, OlegYurchik commented on sapphire/projects/__main__.py
> +from sapphire.projects import get_cli
Здесь бы оставить относительный импорт, как было

2023-10-04 12:52 UTC, OlegYurchik commented on sapphire/projects/database/cli.py
> +    migration_service = ctx.obj["database"]
Давай назовём его `database_service` (так как по факту `migration_service`  у нас нет)

2023-10-04 12:52 UTC, OlegYurchik commented on sapphire/projects/cli.py
> +    cli.add_typer(database.get_cli(), name="database")
Вот тут перед return-ом стояла пустая строка, которая визуально отделяла настройку и возвращение объекта

2023-10-04 13:05 UTC, OlegYurchik approved these changes

2023-10-04 13:17 UTC, vanvanich9 approved these changes

2023-10-04 14:33 UTC, merged