oauth2 первая часть(без взаимодействий с базой)
habralab/sapphire-team-back pull request #4
Opened 2023-09-25 19:03 UTC by brulitsan

2023-09-25 19:34 UTC, vanvanich9 requested changes

2023-09-25 19:34 UTC, vanvanich9 commented on sapphire/users/oauth2/oauth2.py
> +@router.get('/tocken')
token

2023-09-25 19:34 UTC, vanvanich9 commented on sapphire/users/oauth2/oauth2.py
> +async def oauth2(request: web.Request):
web.Request - это aiohttp
ты же пишешь ручку c роутером другого фреймворка
`async def oauth2(code: str, state: str):` - для нашей задачи должно выглядеть так, в этом случае ты запрашиваешь в параметрах code и state как обязательные параметры. Можно и остаться на Request, но тогда импортируй его из FastApi

P.S. я бы еще добавил схемы в response model

2023-09-25 19:34 UTC, vanvanich9 commented on sapphire/users/oauth2/oauth2.py
> +    state = request.query["state"]
это соответственно убрать, если пропишешь аргументы в функции

2023-09-25 19:34 UTC, vanvanich9 commented on sapphire/users/oauth2/oauth2.py
> +    if state != state:
знаю, что данный ужас из моего кода, дай разные имена переменных, по факту у тебя условие всегда True

2023-09-25 19:34 UTC, vanvanich9 commented on sapphire/users/oauth2/oauth2.py
> +    # Getting info about user
Немного не нравится, что у нас в ручке достается токен и сразу же идет за персональными данными. Если мы в дальнейшем хотим забыть об этом токене, но мб и ок (хотя снова же тогда лучше переименовать ручку), в ином случае я бы разбил получение токена и данных пользователя на две разные ручки. Но тут интересно мнение общее, поэтому можно обсудить в чате.

2023-09-25 19:34 UTC, vanvanich9 commented on sapphire/users/oauth2/oauth2.py
> +    return web.Response(text=user_data["user"]["email_normalized"])
респонс из aiohttp

2023-09-25 19:34 UTC, vanvanich9 commented on sapphire/users/oauth2/oauth2.py
> +from  sapphire.users.oauth_schemas.oauth import TokenResponse
такой схемы нет

2023-09-25 19:34 UTC, vanvanich9 commented on sapphire/users/oauth_schemas/__init__.py
> +from .common import ResponseStatus, OKResponse, ErrorResponse
давай придерживаться `sapphire.users...`

2023-09-26 06:43 UTC, closed without merging

2023-09-26 06:43 UTC, OlegYurchik commented
Задача переехала в https://github.com/habralab/sapphire-team-back/pull/5