task/26 Init models for user tables
habralab/sapphire-team-back pull request #9
Opened 2023-09-26 18:47 UTC by vanvanich9

2023-09-26 18:50 UTC, vanvanich9 commented on sapphire/users/database/models.py
> +    user_id = Column(UUID, ForeignKey("users.id"), primary_key=True, default=uuid4)
will be fixed...

2023-09-26 20:14 UTC, OlegYurchik requested changes
Всё хорошо, только одно поле переименовать и перевести в SQLAlchemy 2.0

2023-09-26 20:14 UTC, OlegYurchik commented on sapphire/users/database/models.py
> +    second_name = Column(String, nullable=True)
`last_name` вместо `second_name`

2023-09-26 20:25 UTC, OlegYurchik approved these changes

2023-09-27 06:49 UTC, brulitsan commented
.

2023-09-27 06:49 UTC, brulitsan approved these changes

2023-09-27 06:58 UTC, merged